### ISSUE TITLE
Filename not precise enough?

### ISSUE THREAD

**Issue by Galian5** [Galian5/kata-bank#4]
https://github.com/Galian5/kata-bank/blob/ec3ff7cf0ba8660a7439f11534da6166f28feac9/src/test/resources/bank/account.feature#L1

Not a fan of just account. We have two tests about accounts and some distinction would be nice.

**Comment by mdawid92** [comment]
Or we can use one feature (file), account or sth like that, with two scenarios: list accounts, open accounts.
